<?php
/**
 * Created by PhpStorm.
 * User: akke
 * Date: 08/09/2017
 * Time: 17:20
 */

namespace frontend\views\widgets;


use yii\base\Widget;
use yii\helpers\Html;
use app\models\Category;
use app\models\Brand;
use yii\helpers\VarDumper;

class LeftSidebarWidget extends Widget
{
    public $message;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
    	$categories = new Category;
    	$dataCategories = $categories->getCategoriesByParentID();
        $brands = new Brand();
        $dataBrands = $brands->getAllBrands();
        
        return $this->render('LeftSidebarWidget', [
        	'dataCategories' => $dataCategories,
            'dataBrands' => $dataBrands
        ]);
    }
}