<?php
/**
 * Created by PhpStorm.
 * User: akke
 * Date: 08/09/2017
 * Time: 17:20
 */

namespace frontend\views\widgets;


use yii\base\Widget;
use yii\helpers\Html;
use app\models\Category;

class LeftSidebarWidget extends Widget
{
    public $message;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
    	$categories = new Category;
    	$dataCategories = $categories->getCategoriesByParentID(0);
        return $this->render('LeftSidebarWidget', [
        	'dataCategories' => $dataCategories
        ]);
    }
}